#!/usr/bin/env python3
"""
Vexyon Bridge Daemon
====================
Single source of truth flows one way: shell.json -> Hyprland.

Responsibilities:
  * Read ~/.config/vexyon/shell.json
  * Generate ~/.config/hypr/vexyon-keybinds.lua  (keybinds + mouse binds + workspace binds)
  * Generate ~/.config/hypr/vexyon-settings.lua  (gaps / border / rounding from layout tokens)
  * Generate ~/.config/hypr/vexyon-monitors.lua  (active display profile)
  * Trigger `hyprctl reload` so changes apply live, zero restart
  * Watch shell.json (mtime poll, dependency-free) and regenerate on change

All writes are atomic (temp file + os.replace) so a crash mid-write never corrupts config.

Usage:
  vexyon-bridge.py            # daemon: generate once, then watch forever
  vexyon-bridge.py --oneshot  # generate once and exit (used by install.sh / manual regen)
"""

import json
import os
import sys
import time
import shutil
import subprocess

HOME = os.path.expanduser("~")
VEXYON_DIR = os.path.join(HOME, ".config", "vexyon")
HYPR_DIR = os.path.join(HOME, ".config", "hypr")
SHELL_JSON = os.path.join(VEXYON_DIR, "shell.json")
# Lua config targets (Hyprland >= 0.55). Hyprlang .conf generation was removed
# after the migration was verified end to end; Hyprland 0.57 drops hyprlang.
KEYBINDS_LUA = os.path.join(HYPR_DIR, "vexyon-keybinds.lua")
SETTINGS_LUA = os.path.join(HYPR_DIR, "vexyon-settings.lua")
MONITORS_LUA = os.path.join(HYPR_DIR, "vexyon-monitors.lua")

# Terminal theming targets (regenerated from the active Vexyon palette).
THEMES_DIR = os.path.join(HOME, ".local", "share", "vexyon", "themes")
# Static theme snapshot the greetd greeter reads before any user session
# exists. install.sh seeds it owned by the user precisely so this daemon can
# keep it in sync on theme changes without sudo; on older installs it is
# root-owned and the sync is silently skipped until install.sh runs again.
# On NixOS /etc is Nix-managed (read-only symlinks into the store), so the
# module points VEXYON_GREETER_STATE_DIR at /var/lib/vexyon-greeter instead.
# Default = the Arch path, so nothing changes there.
GREETER_STATE_DIR = os.environ.get(
    "VEXYON_GREETER_STATE_DIR", "/etc/greetd/vexyon-greeter")
GREETER_THEME = os.path.join(GREETER_STATE_DIR, "theme.json")
# Fragmentos Lua que el kiosco del greeter carga con dofile DESPUÉS de su
# propia config, así que pisan sus defectos. Existen para que la pantalla de
# login use el MISMO teclado y el MISMO cursor que la sesión: la contraseña hay
# que teclearla con la distribución del usuario, no con "us".
GREETER_INPUT_LUA = os.path.join(GREETER_STATE_DIR, "input.lua")
GREETER_CURSOR_LUA = os.path.join(GREETER_STATE_DIR, "cursor.lua")

# --- temas de cursor -------------------------------------------------------
# id de appearance.cursorTheme -> nombre del tema XCursor. Todos son temas
# NORMALES y sin marca. No hay opción "sin tema" a propósito: si XCURSOR_THEME
# no se fija (o apunta a un tema que no existe), Hyprland dibuja su cursor
# EMBEBIDO, que tiene la forma de su logo. Por eso cursor_theme_name() nunca
# devuelve cadena vacía.
# Los paquetes que proveen estos nombres los instala nix/module.nix; el mismo
# mapa está replicado en vexyon-greeter-sync-theme (el helper manual).
CURSOR_THEMES = {
    "default": "Adwaita",                  # adwaita-icon-theme — flecha negra clásica
    "pretty": "Bibata-Modern-Ice",         # bibata-cursors — blanca redondeada
    "black": "Bibata-Modern-Classic",      # bibata-cursors — negra redondeada
    "dmz": "Vanilla-DMZ",                  # vanilla-dmz — la blanca clásica de X11
    "capitaine": "capitaine-cursors",      # capitaine-cursors — gris pizarra
}
# "system" era el id viejo de "no fijar ningún tema" — justo el que dejaba
# salir el cursor con forma de logo. Quien lo tenga guardado quería el cursor
# normal del sistema, así que se le da la flecha negra clásica.
CURSOR_ALIASES = {"system": "default"}
CURSOR_FALLBACK = "pretty"  # el de fábrica (shell.json) y el de un id raro
CURSOR_SIZE = "24"
GHOSTTY_CONF = os.path.join(HOME, ".config", "ghostty", "config")
FISH_THEME = os.path.join(HOME, ".config", "fish", "conf.d", "vexyon-theme.fish")
FASTFETCH_CONF = os.path.join(VEXYON_DIR, "fastfetch.jsonc")

POLL_INTERVAL = 0.5  # seconds


LUA_HEADER = (
    "-- ============================================================================\n"
    "--  VEXYON — AUTOGENERATED. DO NOT EDIT BY HAND.\n"
    "--  Edit ~/.config/vexyon/shell.json (or use the Keybind Editor); the bridge\n"
    "--  daemon regenerates this file and reloads Hyprland automatically.\n"
    "-- ============================================================================\n\n"
)


def log(msg):
    print(f"[vexyon-bridge] {msg}", flush=True)


def load_config():
    """Read shell.json. Returns dict or None on failure (caller keeps last good)."""
    try:
        with open(SHELL_JSON, "r") as f:
            return json.load(f)
    except FileNotFoundError:
        log(f"config not found: {SHELL_JSON}")
        return None
    except json.JSONDecodeError as e:
        log(f"invalid JSON in shell.json ({e}); keeping last good config")
        return None


def atomic_write(path, content):
    """Write content to path atomically (temp file in same dir + os.replace).

    Returns True if the on-disk content actually changed (or the file was
    created), False if it already matched byte-for-byte. Callers use this to
    avoid signalling a consumer that nothing relevant changed — e.g. Ghostty
    would pop a "config reloaded" toast on SIGUSR2 even when the rewrite was
    a no-op (a wallpaper change leaves the terminal config identical)."""
    try:
        with open(path, "r") as f:
            if f.read() == content:
                return False
    except (FileNotFoundError, OSError):
        pass
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        f.write(content)
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp, path)
    return True


def fmt_scale(s):
    """1 -> '1', 1.25 -> '1.25' (trim trailing zeros; Hyprland wants a clean float)."""
    try:
        n = float(s)
    except (TypeError, ValueError):
        return "1"
    if n <= 0:
        return "1"
    return ("%f" % n).rstrip("0").rstrip(".") or "1"


# ============================================================================
#  Emisores Lua (Hyprland >= 0.55; hyprlang desaparece en 0.57). Reglas de
#  emisión "lean" (HYPRLAND_LUA_MIGRATION_PLAN.md): UNA llamada hl.config por
#  regeneración, bucles Lua para los binds de workspace, closures hl.dsp.*
#  directas sin funciones envoltorio. Formas verificadas EN VIVO, no deducidas:
#  follow=false para mover sin seguir el foco, bind SIN opts para el equivalente
#  de bindm, y match = regex para las layer rules.
# ============================================================================

def lua_str(s):
    """Arbitrary config text -> safe double-quoted Lua string literal."""
    out = (str(s).replace("\\", "\\\\").replace('"', '\\"')
           .replace("\n", "\\n").replace("\r", "\\r"))
    return f'"{out}"'


def lua_key(mods, key):
    """['SUPER','SHIFT'], 'S' -> Lua key string 'SUPER + SHIFT + S'."""
    return " + ".join(list(mods) + [str(key)])


_LUA_DIRS = {"l": "left", "r": "right", "u": "up", "d": "down"}


def lua_ws(p):
    """Workspace selector: numeric stays a Lua number, else quoted string."""
    p = str(p).strip()
    return p if p.isdigit() else lua_str(p)


def lua_dispatcher(disp, params):
    """Classic dispatcher string -> hl.dsp.* call, or None if unknown.
    Solo los dispatchers que Vexyon usa en shell.json (Keybind Editor incluido);
    uno desconocido se salta con log, igual que una action desconocida — las
    tablas de opts de Lua IGNORAN claves inválidas sin error, así que aquí no
    se inventa nada: cada forma está verificada contra el source de 0.56.1."""
    params = (params or "").strip()
    if disp == "killactive":
        return "hl.dsp.window.close()"
    if disp == "togglefloating":
        return 'hl.dsp.window.float({ action = "toggle" })'
    if disp == "fullscreen":
        mode = "maximized" if params == "1" else "fullscreen"
        return f'hl.dsp.window.fullscreen({{ mode = "{mode}" }})'
    if disp == "togglespecialworkspace":
        return (f"hl.dsp.workspace.toggle_special({lua_str(params)})"
                if params else "hl.dsp.workspace.toggle_special()")
    if disp == "movefocus" and params in _LUA_DIRS:
        return f'hl.dsp.focus({{ direction = "{_LUA_DIRS[params]}" }})'
    if disp == "swapwindow" and params in _LUA_DIRS:
        return f'hl.dsp.window.swap({{ direction = "{_LUA_DIRS[params]}" }})'
    if disp == "workspace":
        return f"hl.dsp.focus({{ workspace = {lua_ws(params)} }})"
    if disp == "movetoworkspace":
        return f"hl.dsp.window.move({{ workspace = {lua_ws(params)} }})"
    if disp == "movetoworkspacesilent":
        return f"hl.dsp.window.move({{ workspace = {lua_ws(params)}, follow = false }})"
    if disp == "exit":
        return "hl.dsp.exit()"
    return None


# Acciones de mouseBinds (bindm clásico). En Lua el equivalente es un bind
# NORMAL (sin opts) con el dispatcher interactivo: se dispara al PULSAR y el
# arrastre sigue al puntero hasta soltar, igual que bindm.
#
# OJO — verificado en vivo, no deducido: `{ drag = true }` NO es el equivalente
# de bindm. En KeybindManager.cpp un bind con `drag` implica `release = true` y
# solo se dispara al SOLTAR el botón y habiendo superado drag_threshold, o sea
# justo cuando ya no se puede arrastrar nada. Y `{ mouse = true }` (lo que trae
# el ejemplo oficial /usr/share/hypr/hyprland.lua) es INERTE: kb.mouse nunca se
# asigna desde las opts en el binding Lua de 0.56.1, solo se lee en una
# validación. Por eso el ejemplo funciona: equivale a un bind sin opts.
_LUA_MOUSE = {
    "movewindow": "hl.dsp.window.drag()",
    "resizewindow": "hl.dsp.window.resize()",
}


def build_keybinds_lua(cfg):
    lines = [LUA_HEADER]
    lines.append("-- --- Static core mouse binds ---\n")
    lines.append('hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })\n')
    for mb in cfg.get("mouseBinds", []):
        dsp = _LUA_MOUSE.get(mb.get("action"))
        if not dsp:
            log(f"unknown mouse action '{mb.get('action')}' for '{mb.get('id')}', skipping")
            continue
        keys = lua_key(mb.get("mods", []), mb["button"])
        lines.append(f"hl.bind({lua_str(keys)}, {dsp})\n")
    lines.append("\n-- --- Named action binds ---\n")

    for kb in cfg.get("keybinds", []):
        keys = lua_key(kb.get("mods", []), kb["key"])
        action = kb["action"]
        arg = kb.get("arg", "")
        if action == "exec":
            dsp = f"hl.dsp.exec_cmd({lua_str(arg)})"
        elif action == "global":
            # Quickshell GlobalShortcut: appid 'quickshell', name = arg
            dsp = f"hl.dsp.global({lua_str('quickshell:' + arg)})"
        elif action == "dispatch":
            parts = arg.split(" ", 1)
            dsp = lua_dispatcher(parts[0], parts[1] if len(parts) == 2 else "")
            if not dsp:
                log(f"no Lua mapping for dispatcher '{arg}' (keybind '{kb.get('id')}'), skipping")
                continue
        else:
            log(f"unknown action '{action}' for keybind '{kb.get('id')}', skipping")
            continue
        # Flags de shell.json: 'l' (locked) y 'e' (repeating);
        # cualquier otro carácter se descarta.
        flags = str(kb.get("flags", ""))
        opts = []
        if "l" in flags:
            opts.append("locked = true")
        if "e" in flags:
            opts.append("repeating = true")
        optstr = f", {{ {', '.join(opts)} }}" if opts else ""
        desc = kb.get("desc", "")
        comment = f"  -- {desc}" if desc else ""
        lines.append(f"hl.bind({lua_str(keys)}, {dsp}{optstr}){comment}\n")

    # --- Workspace switch / move binds: bucles Lua, no 20 líneas desenrolladas ---
    lines.append("\n-- --- Workspace binds (generated from workspaceCount) ---\n")
    count = cfg.get("layout", {}).get("workspaceCount", 10)
    count = max(1, min(count, 10))
    km = cfg.get("keybindMods", {})
    sw = lua_str(" + ".join(km.get("workspaceSwitch", ["SUPER"])) + " + ")
    mv = lua_str(" + ".join(km.get("workspaceMove", ["SUPER", "SHIFT"])) + " + ")
    lines.append(f"for i = 1, {count} do\n")
    lines.append("    local key = i % 10\n")
    lines.append(f"    hl.bind({sw} .. key, hl.dsp.focus({{ workspace = i }}))\n")
    lines.append("    -- NON-silent move: the user FOLLOWS the window to the target workspace.\n")
    lines.append(f"    hl.bind({mv} .. key, hl.dsp.window.move({{ workspace = i }}))\n")
    lines.append("end\n")
    return "".join(lines)


def build_monitors_lua(cfg):
    """Source of truth is shell.json displays.activeProfile;
    emits hl.monitor tables. Empty profile emits nothing so the catch-all
    hl.monitor in hyprland.lua stays in effect (later calls accumulate)."""
    lines = [LUA_HEADER]
    lines.append("-- Generated from shell.json displays.activeProfile.\n")
    disp = cfg.get("displays", {}) or {}
    active = disp.get("activeProfile", "")
    profile = None
    for p in disp.get("profiles", []) or []:
        if p.get("name") == active:
            profile = p
            break
    if not profile or not profile.get("monitors"):
        # Sin perfil activo la geometría la pone hyprland.lua, pero la asignación
        # de workspaces es independiente del perfil: se emite igualmente.
        lines.append("-- (no active profile — hyprland.lua default applies)\n")
        lines.append(build_default_workspaces_lua(cfg))
        return "".join(lines)
    lines.append(f"-- Active profile: {active}\n")
    for name, c in profile["monitors"].items():
        lines.append(lua_monitor_call(name, c) + "\n")
    lines.append(build_default_workspaces_lua(cfg))
    return "".join(lines)


def build_default_workspaces_lua(cfg):
    """Default workspace per monitor, from displays.defaultWorkspaces.

    Keyed by the monitor's EDID description (make + model + serial), never by
    connector: on the real tower the port order does not match the physical
    order (DP-1 left, DP-3 middle, DP-2 right), and two of the panels are the
    same model, so only the serial-bearing description identifies them.

    A rule whose monitor is not currently connected is accepted by Hyprland
    without error and simply matches nothing, so the whole map is emitted
    unconditionally — the assignment comes back by itself on reconnect.
    Empty map emits nothing, i.e. stock Hyprland behaviour."""
    dws = (cfg.get("displays", {}) or {}).get("defaultWorkspaces", {}) or {}
    if not dws:
        return ""
    out = ["\n-- --- Default workspace per monitor (stable EDID description) ---\n"]
    for key, ws in sorted(dws.items()):
        try:
            n = int(ws)
        except (TypeError, ValueError):
            continue
        if n <= 0:
            continue
        out.append(lua_workspace_rule(key, n) + "\n")
    return "".join(out)


def lua_workspace_rule(key, ws):
    """Mirrors Displays.wsRuleCall() in QML so live-apply and the persisted
    config agree. `workspace` must be a string (hl.meta.lua stub)."""
    sel = key if ("-" in key and " " not in key) else f"desc:{key}"
    return (f"hl.workspace_rule({{ workspace = {lua_str(str(ws))}, "
            f"monitor = {lua_str(sel)}, default = true }})")


def lua_monitor_call(name, c):
    """Mirrors Displays.monCall() in QML so live-apply and the persisted
    config agree field by field."""
    if c.get("enabled") is False:
        return f"hl.monitor({{ output = {lua_str(name)}, disabled = true }})"
    mode = f"{c.get('resolution', 'preferred')}@{c.get('refresh', 60)}"
    pos = f"{int(c.get('x', 0))}x{int(c.get('y', 0))}"
    fields = [
        f"output = {lua_str(name)}",
        f"mode = {lua_str(mode)}",
        f"position = {lua_str(pos)}",
        f"scale = {lua_str(fmt_scale(c.get('scale', 1)))}",
        f"transform = {int(c.get('transform', 0))}",
        f"vrr = {int(c.get('vrr', 0))}",
    ]
    if int(c.get("bitdepth", 8)) == 10:
        fields.append("bitdepth = 10")
    return f"hl.monitor({{ {', '.join(fields)} }})"


def build_settings_lua(cfg):
    """ONE hl.config call + the two bar
    layer rules. The col.* gradient uses the Lua table form
    { colors = {...}, angle = 45 } (verified against the shipped example)."""
    layout = cfg.get("layout", {})
    behavior = cfg.get("behavior", {})
    appearance = cfg.get("appearance", {})
    gaps_in = layout.get("gapsIn", 4)
    gaps_out = layout.get("gapsOut", 10)
    border = layout.get("borderSize", 2)
    rounding = layout.get("roundingHypr", 12)
    ffm = 1 if behavior.get("focusFollowsMouse", True) else 0
    kb = str(behavior.get("keyboardLayout", "us")).strip() or "us"
    if not all(c.isalnum() or c in ",_-" for c in kb):
        kb = "us"
    kbv = str(behavior.get("keyboardVariant", "")).strip()
    if not all(c.isalnum() or c in ",_-" for c in kbv):
        kbv = ""
    bar_blur = appearance.get("barBlur", True) is not False
    intensity = appearance.get("barBlurIntensity", 24)
    blur_size = max(2, min(int(intensity / 4), 14))
    colors, _ = load_theme(cfg)
    body = (
        LUA_HEADER
        + "hl.config({\n"
        + "    general = {\n"
        + f"        gaps_in = {gaps_in},\n"
        + f"        gaps_out = {gaps_out},\n"
        + f"        border_size = {border},\n"
        + "        col = {\n"
        + f"            active_border = {{ colors = {{ \"rgba({theme_hex(colors, 'accent')}ff)\", \"rgba({theme_hex(colors, 'accent2')}ff)\" }}, angle = 45 }},\n"
        + f"            inactive_border = \"rgba({theme_hex(colors, 'surface1')}aa)\",\n"
        + "        },\n"
        + "    },\n"
        + "    decoration = {\n"
        + f"        rounding = {rounding},\n"
        + "        blur = {\n"
        + f"            enabled = {'true' if bar_blur else 'false'},\n"
        + f"            size = {blur_size},\n"
        + "            passes = 3,\n"
        + "        },\n"
        + "    },\n"
        + "    input = {\n"
        + f"        kb_layout = {lua_str(kb)},\n"
        + f"        kb_variant = {lua_str(kbv)},\n"
        + f"        follow_mouse = {ffm},\n"
        + "    },\n"
        + "})\n"
    )
    # Cursor. Va como env porque XCURSOR_THEME es lo que lee Hyprland (y todo
    # cliente XCursor) al arrancar; el cambio EN CALIENTE lo hace aparte
    # `hyprctl setcursor`, porque un env nuevo no llega a un compositor que ya
    # está corriendo. SIEMPRE se emite: dejar XCURSOR_THEME sin fijar es lo que
    # saca el cursor embebido de Hyprland (con forma de su logo).
    body += (
        "\n-- Cursor (appearance.cursorTheme). El cambio en vivo lo aplica el\n"
        "-- bridge con `hyprctl setcursor`; esto es lo que persiste al reiniciar.\n"
        f"hl.env(\"XCURSOR_THEME\", {lua_str(cursor_theme_name(cfg))})\n"
        f"hl.env(\"XCURSOR_SIZE\", {lua_str(CURSOR_SIZE)})\n"
    )
    if bar_blur:
        body += (
            "\n-- Blur SOLO en la barra (appearance.barBlur). match = regex, el mismo\n"
            "-- motor que las layerrules clásicas (verificado en el source 0.56.1).\n"
            'hl.layer_rule({ name = "vexyon-bar-blur", match = { namespace = "^(vexyon-bar)$" }, blur = true })\n'
            'hl.layer_rule({ name = "vexyon-bar-alpha", match = { namespace = "^(vexyon-bar)$" }, ignore_alpha = 0.2 })\n'
        )
    return body


# ============================================================================
#  Terminal theming: Ghostty + Fish + fastfetch, all from the active palette.
# ============================================================================
DEFAULTS = {
    "base": "#0d0d12", "mantle": "#0a0a0e", "crust": "#070709",
    "text": "#e6e6ef", "subtext0": "#a6a6c0", "subtext1": "#c2c2d6",
    "surface0": "#16161d", "surface1": "#20202a", "surface2": "#2b2b38",
    "overlay0": "#3a3a4a", "overlay1": "#4c4c60", "overlay2": "#6a6a82",
    "accent": "#e11d48", "accent2": "#f43f5e",
    "red": "#f38ba8", "green": "#a6e3a1", "yellow": "#f9e2af", "blue": "#89b4fa",
    "peach": "#fab387", "mauve": "#cba6f7", "teal": "#94e2d5", "pink": "#f5c2e7",
}


def load_theme(cfg):
    """Return (colors_dict, is_dark) for the active theme, filled with fallbacks."""
    active = (cfg.get("theme", {}) or {}).get("active", "crimson-voltage")
    colors = dict(DEFAULTS)
    is_dark = True
    try:
        with open(os.path.join(THEMES_DIR, active + ".json")) as f:
            data = json.load(f)
        is_dark = data.get("dark", True) is not False
        for k, v in (data.get("colors", {}) or {}).items():
            if v:
                colors[k] = v
    except Exception as e:
        log(f"theme '{active}' not loaded ({e}); using fallback palette")
    if "onAccent" not in colors:
        colors["onAccent"] = "#0b0b0f" if is_dark else "#ffffff"
    return colors, is_dark


def hexstrip(h):
    return h.lstrip("#")


def theme_hex(colors, key):
    """6 dígitos hex validados para sintaxis rgba() de Hyprland — un color
    corrupto en un theme JSON no debe emitir config inválida."""
    s = hexstrip(str(colors.get(key, ""))).lower()
    if len(s) != 6 or any(ch not in "0123456789abcdef" for ch in s):
        s = hexstrip(DEFAULTS[key])
    return s


def hex_to_ansi(h):
    """'#e11d48' -> '38;2;225;29;72' (fastfetch truecolor spec)."""
    s = hexstrip(h)
    try:
        r, g, b = int(s[0:2], 16), int(s[2:4], 16), int(s[4:6], 16)
        return f"38;2;{r};{g};{b}"
    except Exception:
        return "38;2;225;29;72"


def build_ghostty_conf(cfg, c):
    font = (cfg.get("appearance", {}) or {}).get("fontFamily", "JetBrainsMono Nerd Font")
    # ANSI slots: 0-7 normal, 8-15 bright.
    ansi = [c["surface1"], c["red"], c["green"], c["yellow"], c["blue"], c["mauve"],
            c["teal"], c["subtext1"], c["overlay1"], c["red"], c["green"], c["yellow"],
            c["blue"], c["mauve"], c["teal"], c["text"]]
    lines = [
        "# AUTOGENERATED by vexyon-bridge — regenerated on theme change. Do not edit.",
        # Ruta absoluta a fish: ghostty ejecuta `command` sin pasar por el PATH
        # del usuario. En Arch siempre es /usr/bin/fish; en NixOS vive en el
        # store con un hash en la ruta, así que se resuelve en tiempo de
        # generación en vez de codificarse.
        "command = " + (shutil.which("fish") or "/usr/bin/fish"),
        # Super+Q (Hyprland killactive) must close the window instantly even with
        # a foreground process (btop, etc.) — no "close?" confirmation dialog.
        "confirm-close-surface = false",
        # The "Config reloaded" / "Configuración recargada" toast must NEVER
        # appear, whatever triggers the reload (theme change, SIGUSR2, ghostty's
        # own config watcher). `app-notifications` is a flag set: `no-<name>`
        # disables one notification, the rest keep their defaults — so
        # clipboard-copy is untouched. GTK-only key, available since ghostty
        # 1.1.0 (this system runs 1.3.1). A real theme change still reloads and
        # re-colours every open terminal; it just does it silently.
        "app-notifications = no-config-reload",
        f"font-family = {font}",
        f"background = {c['base']}",
        f"foreground = {c['text']}",
        f"cursor-color = {c['accent']}",
        f"selection-background = {c['accent']}",
        f"selection-foreground = {c['onAccent']}",
    ]
    for i, col in enumerate(ansi):
        lines.append(f"palette = {i}={col}")
    return "\n".join(lines) + "\n"


def build_fish_theme(c):
    """Fish syntax-highlight colours + a themed two-tone prompt (native fish)."""
    def s(h):
        return hexstrip(h)
    lines = [
        "# AUTOGENERATED by vexyon-bridge — regenerated on theme change. Do not edit.",
        f"set -g fish_color_normal {s(c['text'])}",
        f"set -g fish_color_command {s(c['blue'])}",
        f"set -g fish_color_keyword {s(c['mauve'])}",
        f"set -g fish_color_quote {s(c['green'])}",
        f"set -g fish_color_redirection {s(c['teal'])}",
        f"set -g fish_color_end {s(c['peach'])}",
        f"set -g fish_color_error {s(c['red'])}",
        f"set -g fish_color_param {s(c['subtext1'])}",
        f"set -g fish_color_comment {s(c['overlay1'])}",
        f"set -g fish_color_operator {s(c['yellow'])}",
        f"set -g fish_color_escape {s(c['pink'])}",
        f"set -g fish_color_autosuggestion {s(c['overlay0'])}",
        f"set -g fish_color_selection --background={s(c['surface2'])}",
        f"set -g fish_color_search_match --background={s(c['surface1'])}",
        f"set -g fish_pager_color_prefix {s(c['accent'])}",
        f"set -g fish_pager_color_progress {s(c['subtext0'])}",
        f"set -g fish_pager_color_selected_background --background={s(c['surface1'])}",
        f"set -g vexyon_accent {s(c['accent'])}",
        f"set -g vexyon_accent2 {s(c['accent2'])}",
        f"set -g vexyon_muted {s(c['subtext0'])}",
        "",
        "function fish_prompt",
        "    set -l st $status",
        "    set_color $vexyon_muted",
        "    echo -n (whoami)'@'(prompt_hostname)' '",
        "    set_color $vexyon_accent",
        "    echo -n (prompt_pwd)",
        "    echo -n ' '",
        "    if test $st -eq 0",
        "        set_color $vexyon_accent2",
        "    else",
        "        set_color $fish_color_error",
        "    end",
        "    echo -n '❯ '",
        "    set_color normal",
        "end",
        "",
    ]
    return "\n".join(lines) + "\n"


def build_fastfetch_conf(c):
    keys = hex_to_ansi(c["accent"])
    title = hex_to_ansi(c["accent2"])
    logo1 = hex_to_ansi(c["accent"])
    logo2 = hex_to_ansi(c["accent2"])
    data = {
        "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
        # Compact "small" logo: the full auto logo (~40 cols wide) overflowed and
        # garbled the output whenever a terminal was tiled narrow (several open at
        # once). The small logo keeps the greeting clean down to half-width tiles.
        "logo": {"type": "small", "padding": {"top": 1, "right": 1},
                 "color": {"1": logo1, "2": logo2}},
        "display": {"separator": "  ", "color": {"keys": keys, "title": title}},
        "modules": [
            {"type": "title", "color": {"user": keys, "at": title, "host": keys}},
            {"type": "separator", "string": "─"},
            {"type": "os", "key": "OS"},
            {"type": "kernel", "key": "Kernel"},
            {"type": "uptime", "key": "Uptime"},
            {"type": "packages", "key": "Packages"},
            {"type": "shell", "key": "Shell"},
            {"type": "terminal", "key": "Terminal"},
            {"type": "wm", "key": "WM"},
            # Compact CPU/disk formats: full defaults ("… (32) @ 3.19 GHz",
            # "… - ext4") overran narrow tiled terminals. Drop cores/freq/fs.
            {"type": "cpu", "key": "CPU", "format": "{name}"},
            {"type": "gpu", "key": "GPU", "format": "{name}"},
            {"type": "memory", "key": "Memory"},
            {"type": "disk", "key": "Disk", "format": "{size-used} / {size-total} ({size-percentage})"},
            "break",
            {"type": "colors", "symbol": "circle"},
        ],
    }
    return json.dumps(data, indent=2) + "\n"


def ghostty_reload():
    """Ghostty reloads its config on SIGUSR2 -> open terminals re-theme live."""
    if shutil.which("pkill"):
        subprocess.run(["pkill", "-SIGUSR2", "ghostty"], check=False,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def regenerate_terminal(cfg):
    colors, _ = load_theme(cfg)
    ghostty_changed = atomic_write(GHOSTTY_CONF, build_ghostty_conf(cfg, colors))
    atomic_write(FISH_THEME, build_fish_theme(colors))
    atomic_write(FASTFETCH_CONF, build_fastfetch_conf(colors))
    # Only signal Ghostty when its config genuinely changed (theme colours or
    # font). A wallpaper change never touches the ghostty config bytes, so we
    # skip the SIGUSR2 and it doesn't flash "config reloaded" across every open
    # terminal. A real theme colour change still reloads so the colours apply.
    if ghostty_changed:
        ghostty_reload()
        log("regenerated ghostty/fish/fastfetch theme + signalled Ghostty reload")
    else:
        log("regenerated fish/fastfetch theme (ghostty config unchanged; no reload)")


def cursor_theme_name(cfg):
    """Nombre del tema XCursor para la elección de appearance.cursorTheme.

    NUNCA devuelve cadena vacía: un id desconocido cae en el de fábrica. Sin
    tema fijado Hyprland usa su cursor embebido, que tiene forma de su logo."""
    appearance = cfg.get("appearance", {}) or {}
    choice = str(appearance.get("cursorTheme", CURSOR_FALLBACK)).strip().lower()
    choice = CURSOR_ALIASES.get(choice, choice)
    return CURSOR_THEMES.get(choice, CURSOR_THEMES[CURSOR_FALLBACK])


def apply_cursor_live(cfg):
    """Aplica el cursor al compositor YA corriendo.

    `hl.env` en el fichero generado solo sirve para el siguiente arranque: un
    proceso vivo no re-lee su entorno. Hyprland expone `hyprctl setcursor` para
    justo esto. Es best-effort: si falla (o si no hay compositor, p. ej. en el
    --oneshot de una instalación), el env generado lo arregla en el siguiente
    inicio de sesión."""
    theme = cursor_theme_name(cfg)
    try:
        subprocess.run(["hyprctl", "setcursor", theme, CURSOR_SIZE],
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                       timeout=5, check=False)
    except (OSError, subprocess.SubprocessError):
        pass


def _write_greeter_fragment(path, content, label):
    """Escribe un fragmento Lua del greeter si se puede y si cambió.

    Mismo contrato que sync_greeter_theme: compare-first y salida silenciosa si
    no hay permiso. En Arch el directorio es de root, así que esto no hace nada
    y el teclado del greeter lo sigue poniendo install.sh /
    vexyon-greeter-sync-theme (con sudo) igual que antes — no hay cambio de
    comportamiento allí. En NixOS el directorio es del usuario y el greeter
    queda sincronizado solo, sin escalar privilegios ni pedir nada."""
    try:
        if os.path.isfile(path):
            if not os.access(path, os.W_OK):
                return
            with open(path) as f:
                if f.read() == content:
                    return
        elif not os.access(os.path.dirname(path), os.W_OK):
            return
        with open(path, "w") as f:
            f.write(content)
            f.flush()
            os.fsync(f.fileno())
        log(f"greeter {label} snapshot synced")
    except OSError as e:
        log(f"greeter {label} sync skipped ({e})")


def sync_greeter_input(cfg):
    """Teclado del greeter = teclado de la sesión.

    Sin esto la pantalla de login se queda en la distribución con la que se
    creó y una contraseña con caracteres que cambian de sitio entre
    distribuciones es INTECLEABLE — el usuario no puede entrar.

    Solo se escribe si el usuario tiene una elección EXPLÍCITA en shell.json:
    si la clave no está, el defecto lo pone el sistema (el módulo de NixOS lo
    pasa por entorno al kiosco) y machacarlo aquí con un "us" inventado
    volvería a romper justo lo que esto arregla."""
    behavior = cfg.get("behavior", {}) or {}
    if "keyboardLayout" not in behavior:
        return
    kb = str(behavior.get("keyboardLayout", "")).strip()
    if not kb or not all(c.isalnum() or c in ",_-" for c in kb):
        return
    kbv = str(behavior.get("keyboardVariant", "")).strip()
    if not all(c.isalnum() or c in ",_-" for c in kbv):
        kbv = ""
    content = (
        "-- Vexyon — greeter input (GENERATED by vexyon-bridge)\n"
        f"hl.config({{ input = {{ kb_layout = {lua_str(kb)}, "
        f"kb_variant = {lua_str(kbv)} }} }})\n"
    )
    _write_greeter_fragment(GREETER_INPUT_LUA, content, "keyboard")


def sync_greeter_cursor(cfg):
    """Cursor del greeter = cursor de la sesión (misma pinta antes y después
    del login). Mismo patrón de snapshot que el tema."""
    content = (
        "-- Vexyon — greeter cursor (GENERATED by vexyon-bridge)\n"
        f"hl.env(\"XCURSOR_THEME\", {lua_str(cursor_theme_name(cfg))})\n"
        f"hl.env(\"XCURSOR_SIZE\", {lua_str(CURSOR_SIZE)})\n"
    )
    _write_greeter_fragment(GREETER_CURSOR_LUA, content, "cursor")


def sync_greeter_theme(cfg):
    """Mirror the active theme JSON into the greeter's /etc snapshot.

    The greeter runs as the `greetd` user before login and cannot read
    ~/.config; it reads /etc/greetd/vexyon-greeter/theme.json instead. The
    snapshot file is user-owned (seeded that way by install.sh) so this write
    needs no privilege escalation. The directory stays root-owned, so no
    temp+rename here: compare-first in-place write. The greeter only parses
    the file once at boot and falls back to its embedded palette on a bad
    parse, so the non-atomic write is harmless."""
    active = (cfg.get("theme", {}) or {}).get("active", "crimson-voltage")
    src = os.path.join(THEMES_DIR, active + ".json")
    if not os.path.isfile(src) or not os.path.isfile(GREETER_THEME):
        return
    if not os.access(GREETER_THEME, os.W_OK):
        return  # pre-user-ownership install; re-running install.sh fixes it
    try:
        with open(src) as f:
            content = f.read()
        parsed = json.loads(content)  # never overwrite a good snapshot with garbage
        if not isinstance(parsed.get("colors"), dict):
            log(f"greeter theme sync skipped: '{active}' has no colors dict")
            return
        with open(GREETER_THEME) as f:
            if f.read() == content:
                return
        with open(GREETER_THEME, "w") as f:
            f.write(content)
            f.flush()
            os.fsync(f.fileno())
        log(f"greeter theme snapshot synced -> {active}")
    except (OSError, ValueError) as e:
        log(f"greeter theme sync skipped ({e})")


def sync_color_scheme(cfg):
    """Expose the active theme's light/dark as the freedesktop color-scheme.

    Writes `org.gnome.desktop.interface color-scheme` — the backing key the
    portal's Settings backend (xdg-desktop-portal-gtk, the declared fallback
    in hyprland-portals.conf) reads. xdg-desktop-portal then broadcasts it to
    apps as `org.freedesktop.appearance color-scheme`; browsers forward it to
    web pages as the `prefers-color-scheme` media query. Event-driven: runs
    only inside regenerate() (shell.json change); compare-first so wallpaper/
    keybind regenerates and already-correct values are a no-op. Sites with
    their own theme toggle ignore the preference by design — out of our hands."""
    if not shutil.which("gsettings"):
        return  # glib2 missing (non-standard install); nothing to sync into
    _, is_dark = load_theme(cfg)
    want = "prefer-dark" if is_dark else "prefer-light"
    try:
        cur = subprocess.run(
            ["gsettings", "get", "org.gnome.desktop.interface", "color-scheme"],
            capture_output=True, text=True, timeout=5).stdout.strip().strip("'")
        if cur == want:
            return
        subprocess.run(
            ["gsettings", "set", "org.gnome.desktop.interface", "color-scheme", want],
            check=False, timeout=5,
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        log(f"color-scheme -> {want}")
    except Exception as e:
        log(f"color-scheme sync skipped ({e})")


def hyprctl_reload():
    if not shutil.which("hyprctl"):
        log("hyprctl not found; skipping reload (not in a Hyprland session?)")
        return
    try:
        subprocess.run(["hyprctl", "reload"], check=False,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=10)
        log("hyprctl reload triggered")
    except Exception as e:
        log(f"hyprctl reload failed: {e}")


def regenerate(cfg, reload=True):
    atomic_write(KEYBINDS_LUA, build_keybinds_lua(cfg))
    atomic_write(SETTINGS_LUA, build_settings_lua(cfg))
    atomic_write(MONITORS_LUA, build_monitors_lua(cfg))
    log(f"regenerated {os.path.basename(KEYBINDS_LUA)} + {os.path.basename(SETTINGS_LUA)} + {os.path.basename(MONITORS_LUA)}")
    regenerate_terminal(cfg)
    sync_greeter_theme(cfg)
    sync_greeter_input(cfg)
    sync_greeter_cursor(cfg)
    sync_color_scheme(cfg)
    if reload:
        hyprctl_reload()
    # Después del reload: `hyprctl reload` NO re-lee el entorno de un proceso ya
    # vivo, así que el hl.env generado solo valdría para el siguiente arranque.
    # Esta llamada es la que hace que el cambio de cursor se vea sin cerrar
    # sesión. Idempotente: setcursor con el mismo tema no parpadea.
    apply_cursor_live(cfg)


def main():
    oneshot = "--oneshot" in sys.argv
    cfg = load_config()
    if cfg is None:
        log("no valid config on startup; nothing to generate")
        if oneshot:
            sys.exit(1)
    else:
        # On the very first generation don't reload if oneshot from installer
        regenerate(cfg, reload=not oneshot)

    if oneshot:
        return

    last_mtime = os.path.getmtime(SHELL_JSON) if os.path.exists(SHELL_JSON) else 0
    last_good = cfg
    log("watching shell.json for changes...")
    while True:
        time.sleep(POLL_INTERVAL)
        try:
            mtime = os.path.getmtime(SHELL_JSON)
        except FileNotFoundError:
            continue
        if mtime == last_mtime:
            continue
        last_mtime = mtime
        new_cfg = load_config()
        if new_cfg is None:
            continue  # malformed; keep last good, wait for next save
        if new_cfg == last_good:
            continue  # touched but identical
        last_good = new_cfg
        log("shell.json changed -> regenerating + reloading")
        regenerate(new_cfg, reload=True)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
