-- ============================================================================
--  VEXYON — WINDOW & LAYER RULES
--
--  Lua API (Hyprland >= 0.55): reglas con tabla nombrada —
--      hl.layer_rule({ name = "…", match = { namespace = "…" }, <efecto> = <valor> })
--
--  El blur de la barra (appearance.barBlur en shell.json) lo emite el BRIDGE
--  en vexyon-settings.lua: decoration.blur.enabled = true/false + las dos
--  hl.layer_rule (blur + ignore_alpha) sobre el namespace vexyon-bar.
--  Los popups usan otros namespaces sin regla => no se desenfocan (spec).
--  No dupliques esas reglas aquí.
--
--  La regla que impide que la PRIMERA ventana del shell (Ajustes / gestor de
--  ficheros) se abra en el monitor del LOGIN también la emite el BRIDGE, en
--  vexyon-settings.lua: `hl.window_rule({ match = { class = "org.quickshell" },
--  workspace = "unset" })`. Va ahí y no aquí porque vexyon-seed copia-si-no-
--  existe y NUNCA pisa este fichero: puesta aquí, la corrección no llegaría a
--  ninguna instalación ya sembrada. Tampoco la dupliques.
-- ============================================================================
