-- ============================================================================
--  VEXYON — AUTOGENERATED. DO NOT EDIT BY HAND.
--  Edit ~/.config/vexyon/shell.json (or use the Keybind Editor); the bridge
--  daemon regenerates this file and reloads Hyprland automatically.
-- ============================================================================

hl.config({
    general = {
        gaps_in = 4,
        gaps_out = 10,
        border_size = 2,
    },
    decoration = {
        rounding = 12,
        blur = {
            enabled = false,
            size = 6,
            passes = 3,
        },
    },
    input = {
        follow_mouse = 1,
    },
})

-- Cursor (appearance.cursorTheme). El cambio en vivo lo aplica el
-- bridge con `hyprctl setcursor`; esto es lo que persiste al reiniciar.
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "24")
