-- ============================================================================
--  VEXYON — AUTOGENERATED. DO NOT EDIT BY HAND.
--  Edit ~/.config/vexyon/shell.json (or use the Keybind Editor); the bridge
--  daemon regenerates this file and reloads Hyprland automatically.
-- ============================================================================

hl.config({
    general = {
        gaps_in = 4,
        gaps_out = 10,
        border_size = 2,
    },
    decoration = {
        rounding = 12,
        blur = {
            enabled = false,
            size = 6,
            passes = 3,
        },
    },
    input = {
        follow_mouse = 1,
    },
})

-- Cursor (appearance.cursorTheme). El cambio en vivo lo aplica el
-- bridge con `hyprctl setcursor`; esto es lo que persiste al reiniciar.
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "24")

-- Ventanas del propio shell (Ajustes, ficheros): fuera del
-- initial_workspace_tracking de Hyprland, que las clavaba en el workspace
-- donde arrancó quickshell (el 1) en vez del que mira el usuario.
hl.window_rule({ name = "vexyon-shell-ws-unset", match = { class = [[^(org\.quickshell)$]] }, workspace = "unset" })

-- Overlay de captura: SIN animación de capa. Con el fade de salida, grim
-- disparaba antes de que terminara y el PNG guardado salía con el tinte de
-- la selección dentro.
hl.layer_rule({ name = "vexyon-screenshot-noanim", match = { namespace = "^(vexyon-screenshot)$" }, no_anim = true })
