-- ============================================================================
--  VEXYON — AUTOGENERATED. DO NOT EDIT BY HAND.
--  Edit ~/.config/vexyon/shell.json (or use the Keybind Editor); the bridge
--  daemon regenerates this file and reloads Hyprland automatically.
-- ============================================================================

-- --- Static core mouse binds ---
hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })
-- bindm equivalent = bind NORMAL sin opts (se dispara al pulsar y el arrastre
-- sigue al puntero). `{ drag = true }` NO sirve: implica release=true y solo
-- dispara al soltar; `{ mouse = true }` del ejemplo oficial es inerte.
hl.bind("SUPER + mouse:272", hl.dsp.window.drag())
hl.bind("SUPER + mouse:273", hl.dsp.window.resize())

-- --- Named action binds ---
hl.bind("SUPER + T", hl.dsp.exec_cmd("ghostty"))  -- Open terminal (Ghostty + Fish)
hl.bind("SUPER + Q", hl.dsp.window.close())  -- Kill window under cursor
hl.bind("SUPER + A", hl.dsp.global("quickshell:launcher"))  -- Open App Launcher
hl.bind("SUPER + E", hl.dsp.global("quickshell:filemanager"))  -- Open File Manager
hl.bind("SUPER + B", hl.dsp.exec_cmd("vexyon-open-browser"))  -- Open default browser
hl.bind("SUPER + C", hl.dsp.global("quickshell:controlcenter"))  -- Open Control Center
hl.bind("SUPER + W", hl.dsp.window.float({ action = "toggle" }))  -- Toggle floating for window under cursor
hl.bind("SUPER + ALT + W", hl.dsp.global("quickshell:wallpaper"))  -- Open Wallpaper Picker
hl.bind("SUPER + S", hl.dsp.workspace.toggle_special("scratchpad"))  -- Toggle Scratchpad
hl.bind("SUPER + SHIFT + S", hl.dsp.window.move({ workspace = "special:scratchpad", follow = false }))  -- Send window under cursor to Scratchpad
hl.bind("SUPER + left", hl.dsp.focus({ direction = "left" }))  -- Move focus left
hl.bind("SUPER + right", hl.dsp.focus({ direction = "right" }))  -- Move focus right
hl.bind("SUPER + up", hl.dsp.focus({ direction = "up" }))  -- Move focus up
hl.bind("SUPER + down", hl.dsp.focus({ direction = "down" }))  -- Move focus down
hl.bind("SUPER + SHIFT + left", hl.dsp.window.swap({ direction = "left" }))  -- Swap window left
hl.bind("SUPER + SHIFT + right", hl.dsp.window.swap({ direction = "right" }))  -- Swap window right
hl.bind("SUPER + SHIFT + up", hl.dsp.window.swap({ direction = "up" }))  -- Swap window up
hl.bind("SUPER + SHIFT + down", hl.dsp.window.swap({ direction = "down" }))  -- Swap window down
hl.bind("Print", hl.dsp.global("quickshell:screenshot"))  -- Interactive screenshot / snip
hl.bind("SUPER + L", hl.dsp.global("quickshell:lock"))  -- Lock screen
hl.bind("SUPER + X", hl.dsp.global("quickshell:powermenu"))  -- Power menu

-- --- Workspace binds (generated from workspaceCount) ---
for i = 1, 10 do
    local key = i % 10
    hl.bind("SUPER + " .. key, hl.dsp.focus({ workspace = i }))
end
for i = 1, 10 do
    local key = i % 10
    hl.bind("SUPER + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end
